### PR TITLE
feat: Fix CI build

### PR DESCRIPTION
**Pull request by Hebilicious**
Congratulations on the launch !

Just a couple CI things :
 - Uses setup-node v3 that has cache by default
 - Uses npm over yarn since your package.json uses npm

### CODE REVIEW

**Comment by Hebilicious** [comment]
All things considered, running `cabal build contract` in CI is really long... Hopefully with docker layering it won't be rebuilding everything from scratch all the time and will be faster on the next runs

**Comment by alessandrokonrad** [comment]
@Hebilicious Thank you! I'm gonna check it out later or tomorrow👍🏻

**Comment by Hebilicious** [comment]
> @Hebilicious Thank you! I'm gonna check it out later or tomorrow👍🏻

@alessandrokonrad I can comment out the Haskell build until I figure out what's going on... Can't get it to work on Docker or on MacOS 🤔

**Comment by alessandrokonrad** [comment]
> > @Hebilicious Thank you! I'm gonna check it out later or tomorrow👍🏻
> 
> @alessandrokonrad I can comment out the Haskell build until I figure out what's going on... Can't get it to work on Docker or on MacOS 🤔

Yeah that would be a good idea👍🏻

**Comment by Hebilicious** [comment]
> > > @Hebilicious Thank you! I'm gonna check it out later or tomorrow👍🏻
> > 
> > 
> > @alessandrokonrad I can comment out the Haskell build until I figure out what's going on... Can't get it to work on Docker or on MacOS 🤔
> 
> Yeah that would be a good idea👍🏻

I've commented out the on-chain build, this should be good to merge 🚀

**Comment by Hebilicious** [comment]
@alessandrokonrad Btw, have I wanted to know if you have managed/tried to build locally without nix ? 

I also have started working on a plutus standard for NFTs, opened an issue [here](https://github.com/Berry-Pool/nft-plutus/issues/1) to let you know.
Might be easier to DM, my discord is Hebilicious#3910

**Comment by alessandrokonrad** [comment]
> @alessandrokonrad Btw, I wanted to know if you have managed/tried to build locally without nix ?

I do not use nix here. You only need cabal and ghc.

> I also have started working on a plutus standard for NFTs, opened an issue https://github.com/Berry-Pool/nft-plutus/issues/1 to let you know.
Might be easier to DM, my discord is Hebilicious#3910

Cool I'll take a look and will DM you

**Pull request merged**
